version: 0.2

phases:
  build:
    commands:
       #- chmod +x ./mvnw
       - mvn package
  post_build:
    commands:
      - echo $(basename ./target/*.war)
      - pwd
  artifacts:
    files:
      - target/*.war
  discard-paths: yes


