version: 0.2

phases:
  build:
    commands:
       #- chmod +x ./mvnw
       - mvn package
  post_build:
    commands:
      - pwd
artifacts:
  files:
    - appspec.yml
    - target/*.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'

