version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.war
    - appspec.yml
    - Dockerfile
    - scripts/*
cache:
  paths:
    - '/root/.m2/**/*'
